<?php

namespace AppBundle\Repository;

/**
 * MinifigureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MinifigureRepository extends \Doctrine\ORM\EntityRepository
{
}
