<?php

namespace AppBundle\Repository;

/**
 * SetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SetRepository extends \Doctrine\ORM\EntityRepository
{
}
